config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #resources :phones
  resources :operators
  resources :users
  resources :phonebook
  get '/phone_book/export_to_excel', to: 'phonebook#export_to_excel'
  root 'main#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cabinet.rb
# frozen_string_literal: true

class Cabinet < ApplicationRecord
  validates :number, presence: true, format: { with: /[0-9]{3}[A-Za-z]*/ }
  has_many :users

  before_validation :add_zero

  private

  def add_zero
    self.number = number.rjust(3, '0') unless number.nil?
  end
end

app/models/department.rb
# frozen_string_literal: true

class Department < ApplicationRecord
  validates :title, presence: true

  has_many :user
end

app/models/internal_phone.rb
# frozen_string_literal: true

class InternalPhone < ApplicationRecord
  validates :number, :operator_id, presence: true
  belongs_to :operator
  belongs_to :user
end

app/models/mobile_phone.rb
# frozen_string_literal: true

class MobilePhone < ApplicationRecord
  validates :number, :operator_id, presence: true
  belongs_to :operator
  belongs_to :user
end

app/models/operator.rb
# frozen_string_literal: true

class Operator < ApplicationRecord
  validates :name, presence: true
  has_many :mobile_phones
  has_many :internal_phones
end

app/models/position.rb
# frozen_string_literal: true

class Position < ApplicationRecord
  validates :title, presence: true

  has_many :users
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  validates :fname, :lname, presence: true, format: { with: /\A[A-zА-яЁё]+\z/ }
  validates :pname, format: { with: /\A[A-zА-яЁё]+\z/ }, if: :pname

  belongs_to :cabinet, optional: true
  belongs_to :position, optional: true
  belongs_to :department, optional: true
  has_many :mobile_phones
  has_many :internal_phones

  before_save :down_case

  def all_mobile_phones
    # mobile_phones.map(&:number).join("\n")
    arr = mobile_phones.each_with_object([]) do |obj, accum|
      accum << obj.number
    end
    arr.join("\n").html_safe
  end

  def all_internal_phones
    internal_phones.map(&:number).join("\n")
  end

  def full_name
    name = "#{lname.capitalize} #{fname[0].upcase}"
    pname ? "#{name}.#{pname[0].upcase}." : "#{name}."
  end

  private

  def down_case
    self.email = email.downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cabinets_controller.rb
# frozen_string_literal: true

class CabinetsController < ApplicationController
  def index
    @cabinets = Cabinet.order(:number)
    @users = User.all
  end

  private

  def set_params
    @cabinet = Cabinet.find(params[:id])
  end

  def cabinet_params
    params.require(:cabinet).permit(:number)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @users = User.order(:lname)
  end
end

app/controllers/operators_controller.rb
# frozen_string_literal: true

class OperatorsController < ApplicationController
  before_action :set_operator, only: %i[show edit update destroy]

  def index
    @operators = Operator.order(:name)
  end

  def show; end

  private

  def set_operator
    @operator = Operator.find(params[:id])
  end

  def operator_params
    params.require(:operator).permit(:name)
  end
end

app/controllers/phonebook_controller.rb
# frozen_string_literal: true

class PhonebookController < ApplicationController
  include ActionView::Rendering
  def index
    @phonebook = User.order(:lname)
  end

  def show
    @user = User.find(params[:id])
  end

  def export_to_excel
    @phone_book = User.all
    respond_to do |format|
      format.html
      format.xlsx do
        response.headers['Content-Disposition'] = 'attachment; filename="official_letters.xlsx"'
      end
    end
  end

  private

  def render_to_body(options)
    _render_to_body_with_renderer(options) || super
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index
    @users = User.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cabinets_helper.rb
module CabinetsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/phonebook_helper.rb
module PhonebookHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cabinets/_cabinet.html.erb
<div>
  <tr>
    <td><%= cabinet.number %></td>
    <% cabinet.users.each do |user| %>
      <td><%= user.full_name %></td>
    <% end %>
  </tr>
</div>

app/views/cabinets/index.html.erb
<div class="table_1">
  <table width="100%" cellspacing="0" cellpadding="0">
    <tr align="center"><td class="td">Phones</td></tr>
    <tr align="center"><td class="td"><%= render @cabinets %></td></tr>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Типография АО "Красная Звезда"</title>
    <%= favicon_link_tag 'logo_min.svg' %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <div class="menu">
    <table class="main-menu">
      <tr>
        <td>
          <%= link_to 'Home', root_path %>
        </td>
        <td>
          <%= link_to 'Phones', phonebook_index_path %>
        </td>
        <td>
          <%=  link_to 'About', '/' %>
        </td>
        <td>
        <%=link_to 'Download as Excel', phone_book_export_to_excel_path(format: :xlsx) %>
        </td>
        <td onclick="document.location='3-printers.html'">Принтеры</td>
        <td onclick="document.location='4-cameras.html'">IP-видеокамеры</td>
        <td onclick="document.location='5-video.html'">Видеорегистраторы</td>
      </tr>
    </table>
  </div>
  <div>
    <header>
    </header>
  </div>
    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<p>
  Main
</p>

app/views/phonebook/index.html.erb
<div class="phone_book">
  <table>
    <tr>
      <th colspan="6">Телефонная книга</th>
    </tr>
    <tr>
      <th>ФИО</th>
      <th>Должность</th>
      <th>Отдел</th>
      <th>Мобильный</th>
      <th>Внутренний</th>
    </tr>
    <% @phonebook.each do |phone_line| %>
    <tr>
      <td><%= phone_line.full_name %></td>
      <td><%= phone_line.position.title %></td>
      <td><%= phone_line.department.title %></td>
      <td>
        <%= phone_line.all_mobile_phones.gsub("\n","<br>").html_safe %>
      </td>
      <td>
        <%= phone_line.all_internal_phones.gsub("\n","<br>").html_safe %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/users/_user.html.erb
<tr>
  <td><%= user.full_name %></td>
  <td><%= user.position.title %></td>
  <td><%= user.department.title %></td>
  <td><%= user.cabinet.number %></td>
  <td><%= render user.phones %></td>
</tr>

app/views/users/index.html.erb
<div>
  <table cellspacing="2" border="5" cellpadding="5" width="80%" height="20%" cols="6" rules="all">
    <thead>
    <th colspan="6">
      Phones
    </th>
    </thead>
    <tr>
      <th>ФИО</th>
      <th>Должность</th>
      <th>Отдел</th>
      <th>Кабинет</th>
      <th>Телефон внутренний</th>
      <th>Телефон мобильный</th>
    </tr>
    <tr>
      <td><%= render @users %></td>
    </tr>
  </table>
</div>